[project]
name = "project-2-minio-wr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "minio==7.2.20",
    "python-dotenv==1.2.1",
]
